### ISSUE TITLE
Privacy guide - Ungoogled Chromium

### ISSUE THREAD

**Issue by Eirikr70** [PussTheCat-org/PussTheCat.org-Wiki#2]
Hello, I have much learnt from your privacy guide and am in the process of switching to GrapheneOS. I just wanted to draw your attention on a specific point in that privacy guide. You recommend Ungoogled Chromium as a privacy friendly browser, but it seems that it presents some drawbacks as presented [in this article](https://qua3k.github.io/ungoogled/). I leave it to you, of course, to reconsider your point of view or to maintain the advice.

**Comment by TheFrenchGhosty** [comment]
@Eirikr70 Hello,

First things first: sorry that I didn't reply before, I did read this issue (and the article) the day it was opened, but I didn't have time to reply... then I completely forgot about it.

So:

I am aware that Ungoogled Chromium isn't ideal, yes, but it sadly is the "least bad" Chrom* browser. Today, I wouldn't recommend anyone to use one of the Chrom* browser as their main browser, simply because of the fact that manifest V3 is coming, something that will make it impossible to have a *good* browser.

The article indeed lists some *problem* however the conclusion that says "use Chrome" is awful, simply because even if you disable the stuff in the settings, a ton of spyware remain (and let's not talk about the fact that it's proprietary).

To conclude, I won't change my recommendation, however I might add some more explanation that any Chrom* browser should be avoided.

Thank you :)
